language: python
python:
- '3.3'
script:
- mkdocs build --site-dir site
sudo: false
notifications:
  slack:
    secure: c0erbTCVfcKgqGYAl935piI7t0dm9WjZ1NWqYyp3ZXoCt0bYBj17i29ph7FAawjKqQr0SO8lhxuNPQCVMmr2CqgW1+uiIUXj+ogTyAipKoPLzhhTrl9fYLoZCmqTkIlqZHmBhzzyNXwkbu5OoiEVDSuTAhgEFimzMq12mSumrUh441ohmVO4qrY3EXr5O1meTqPMAqk+pIjZiuzmCYwicYzoMokQdYK63GaIKAvrcEC/em65wmwahHhBnPVgEPGpVpjEUOPRvhKRdmln+HdvlhoRmLVZvhwkBJ+enhgMHQUgNk/INLKjSmfyVxEGnTj93EgrNzbTRsFby5ZJTNvBDLobqME57N5hOn5hQby4ZFkY73kQSSh7Ko6AufZtNz/Kc9YD3CCA+3Bo11jFvPSnO5QNp7tJis62EfhTN9T2oFY7aYVLFL4kHlMWCyidDeWqgNjcVjI+ruSyznAv0mZLxlQ+dX1h6N5VpW5nitBU7TvWDeA8JjJweScLmaaXhxMX3vIldCaCRE1usQjGXgNb/jWhnDPmks/4OE87NX6F6iR3gBZ6CZhWQXtW5zmGDHL/qSNQe2SCel1YOk5h5ihM1JWcgKEK+jtY7mseiFnyTD7EigOaTykjp3LrE0OxZYmaAmQg2lzzxhsbq1UB7VPivYvpvRnoGIQuWa+l6PHoydk=
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
